# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mundipagg-ruby"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael Lima"]
  s.date = "2012-07-13"
  s.description = "Biblioteca Ruby para utilização do gateway MundiPagg"
  s.email = "contato@rafael.adm.br"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.mkdn"
  ]
  s.files = [
    ".bundle/config",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.mkdn",
    "Rakefile",
    "VERSION",
    "mundipagg-ruby.gemspec",
    "lib/mundipagg-ruby.rb",
    "lib/hash_strip_values.rb",
    "spec/mundipagg-ruby_spec.rb",
    "spec/fixtures/cancelamento_marcado_erro.xml",
    "spec/fixtures/cancelamento_marcado_sucesso.xml",
    "spec/fixtures/cancelamento_online_erro.xml",
    "spec/fixtures/cancelamento_online_sucesso.xml",
    "spec/fixtures/config-cgi.yml",
    "spec/fixtures/config.yml",
    "spec/fixtures/dirty_data_structure.xml",
    "spec/fixtures/dummy-config.yml",
    "spec/fixtures/resultado_apc_erro.xml",
    "spec/fixtures/resultado_apc_sucesso.xml",
    "spec/fixtures/resultado_cap_erro.xml",
    "spec/fixtures/resultado_cap_sucesso.xml",
    "spec/hash_strip_values_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/rafaelp/mundipagg-ruby"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby wrapper for MundiPagg webservice"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, ["= 1.1.1"])
      s.add_development_dependency(%q<rspec>, ["= 2.3.0"])
      s.add_development_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_development_dependency(%q<bundler>, ["= 1.1.4"])
      s.add_development_dependency(%q<jeweler>, ["= 1.8.4"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_runtime_dependency(%q<xml-simple>, [">= 1.1.1"])
    else
      s.add_dependency(%q<xml-simple>, ["= 1.1.1"])
      s.add_dependency(%q<rspec>, ["= 2.3.0"])
      s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_dependency(%q<bundler>, ["= 1.1.4"])
      s.add_dependency(%q<jeweler>, ["= 1.8.4"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<xml-simple>, [">= 1.1.1"])
    end
  else
    s.add_dependency(%q<xml-simple>, ["= 1.1.1"])
    s.add_dependency(%q<rspec>, ["= 2.3.0"])
    s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
    s.add_dependency(%q<bundler>, ["= 1.1.4"])
    s.add_dependency(%q<jeweler>, ["= 1.8.4"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<xml-simple>, [">= 1.1.1"])
  end
end

